FROM python:3.12.2
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "drf-yasg[validation]"
RUN pip install git+https://github.com/atomic-loops/atomicloops-django-logger
WORKDIR /opt
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]